[package]
name = "mkl26"
version = "0.1.0"
authors = ["Gabriel Smith <ga29smith@gmail.com>"]

[dependencies]
arraydeque = { version = "^0.2", default-features = false }
bare-metal = "^0.1"
bit_field = "^0.8"
cortex-m = "^0.4"
cortex-m-rt = { version = "0.3.12", features = ["init_array"] }
volatile-register = "^0.2"

[features]
default = ["i2c-isr", "i2c-slave", "i2c-dma", "fgpio"] # default to everything on for docs

fgpio = []

i2c-isr = []
i2c-slave = ["i2c-isr"]
i2c-dma = ["i2c-isr"]

[[example]]
name = "blink"

[patch.crates-io]
cortex-m-rt = { git = "https://github.com/yodaldevoid/cortex-m-rt.git", branch = "init_array" }
