[package]
name = "rusty_teensy"
version = "0.1.0"
authors = ["Gabriel Smith <ga29smith@gmail.com>"]

[dependencies]
cortex-m = "^0.3"
volatile-register = "^0.2"
bare-metal = "^0.1"
bit_field = "^0.8"
cortex-m-rt = "^0.3"
